### ISSUE TITLE
Crash on interact with merchant

### ISSUE THREAD

**Issue by Spectre0987** [Ivasik78/Tale-of-Kingdoms#1]
When the player interacts with any merchant (Backsmith, cook, ect...) it crashes.
[CrashLog.log](https://github.com/Ivasik78/Tale-of-Kingdoms/files/1443488/CrashLog.log)

**Comment by Ivasik78** [comment]
I know about this problem in the near future will fix it.

**Comment by Ivasik78** [comment]
@Spectre0987, download the mod from the forgecurse and check it again.
