### ISSUE TITLE
Global Entity ID usage

### ISSUE THREAD

**Issue by Gamerbolts** [Ivasik78/Tale-of-Kingdoms#2]
Hi decided to make an official post on your github. So now a new problem, I run the game and it crashes with No More Entity Indicies left. I searched and people said that is caused by the mod using global entity IDs. Is there a way you can change that? I know nothing about coding so do not know what that entails. If you could change entities from Global though that would be amazing.

I did some checking and ToK uses 40 Global Entity IDs

https://pastebin.com/TNA2CPsR

**Comment by Ivasik78** [comment]
Fixed
